// Generated by CoffeeScript 1.7.1
(function() {
	
  var app = angular.module('selectAddress', []);
  app.directive('selectAddress', function($http, $q, $compile) {
    var cityURL, delay, templateURL, baseUrl="";
    delay = $q.defer();
    templateURL = Url.getWebRoot('static/js/angularjs/index.html');
  delay.resolve();
    return {
      restrict: 'A',
      scope: {
        p: '=',
        a: '=',
        c: '=',
        d: '=',
        regionName: '=',
        regionCode: '=',
        ngModel: '='
      },
      link: function(scope, element, attrs) {
        element.attr("readonly","readonly");
        element.css({"background-color":"#fff","cursor":"default"});
    	$('.select-address').removeClass('actiove')
    	var popup;
        popup = {
          element: null,
          backdrop: null,
          show: function() {
        	  return this.element.addClass('active');
          },
          hide: function() {
            this.element.removeClass('active');
            return false;
          },
          resize: function() {
            if (!this.element) {
              return;
            }
            this.element.css({
              top: -this.element.height() - 30,
              'margin-left': -this.element.width() / 2
            });
            return false;
          },
          focus: function() {
            $('[ng-model="d"]').focus();
            return false;
          },
          init: function() {
          	
            element.on('click keydown', function() {
              popup.selText = this;
              popup.show();
              event.stopPropagation();
              return false;
            });
            
            $(window).on('click', (function(_this) {
              return function() {
              	if($(_this.element).hasClass('active'))
                	return _this.hide();
              };
            })(this));
            
            this.element.on('click', function() {
              return event.stopPropagation();
            });
            return setTimeout((function(_this) {
              return function() {
                _this.element.show();
                return _this.resize();
              };
            })(this), 500);
          }
        };
        return delay.promise.then(function(data) {
          data = $.Region.getData();
          $http.get(templateURL).success(function(tp) {
            var $tp;
            $tp = $compile(tp)(scope);
            $('body').append($tp);
            popup.element = $($tp[2]);
            scope.provinces = data;
            return popup.init();
          });
          
          scope.aSet = {
            p: function(p) {
              scope.p = p;
              scope.c = null;
              scope.a = null;
              return scope.d = null;
            },
            c: function(c) {
              scope.c = c;
              scope.a = null;
              return scope.d = null;
            },
            a: function(a) {
              scope.a = a;
              scope.d = null;
              return popup.focus();
            }
          };
          
          scope.clear = function() {
            scope.p = null;
            scope.c = null;
            scope.a = null;
            scope.d = null;
            scope.regionName = '';
            scope.regionCode = '';
            $(popup.selText).val('')
            $(popup.selText).parent().find('input').val('')
            return popup.hide();
          };
          
          scope.submit = function() {
          	scope.regionCode = scope.c.id;
          	$(popup.selText).val(scope.regionName)
          	$(popup.selText).siblings('input[name=regionCode]').val(scope.regionCode)
          	$(popup.selText).siblings('input[name=province]').val(scope.p.id)
            $(popup.selText).siblings('input[name=city]').val(scope.c.id)
            $(popup.selText).siblings('input[name=district]').val(scope.a?scope.a.id:'')
            $(popup.selText).siblings('input[name=full_name]').val(scope.p.full+' '+scope.c.full+' '+(scope.a?scope.a.name:''));
            
            return popup.hide();
          };
          
          scope.$watch('p', function(newV, oldV, scope) {
            var v, _i, _len, _results;
            if (newV) {
              _results = [];
              for (_i = 0, _len = data.length; _i < _len; _i++) {
                v = data[_i];
                if (v.id === newV.id) {
                  _results.push(scope.cities = v.c);
                }
              }
              return _results;
            } else {
              return scope.cities = [];
            }
          });
          
          scope.$watch('c', function(newV, oldV, scope) {
            var v, _i, _len, _ref, _results;
            if (newV) {
              _ref = scope.cities;
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                v = _ref[_i];
                if (v.id === newV.id) {
                  _results.push(scope.dists = v.c);
                }
              }
              return _results;
            } else {
              return scope.dists = [];
            }
          });
          
          scope.$watch('regionCode', function(newV, oldV, scope) {
	          if(newV!=undefined && newV!="" && newV!= oldV)
	          {	
          		//触发地址变更时间[触发两次change事件**]
            	$(popup.selText).trigger('change')
	          }
          });
          
          return scope.$watch(function() {
            scope.regionName = '';
            scope.regionCode = '';
            if (scope.p) {
              scope.regionName += scope.p.name;
            }
            if (scope.c) {
              scope.regionName += " " + scope.c.name;
            }
            if (scope.a) {
              scope.regionName += " " + scope.a.name;
              scope.regionCode = scope.a.id;
              
              if(popup.selText!=undefined)
              {
	              $(popup.selText).val(scope.regionName)
	              $(popup.selText).siblings('input[name=regionCode]').val(scope.regionCode)
	              $(popup.selText).siblings('input[name=province]').val(scope.p.id)
	              $(popup.selText).siblings('input[name=city]').val(scope.c.id)
	              $(popup.selText).siblings('input[name=district]').val(scope.a?scope.a.id:'')
	              
	              $(popup.selText).siblings('input[name=full_name]').val(scope.p.full+' '+scope.c.full+' '+(scope.a?scope.a.name:''));
	              popup.hide();
              }
            }
            
            if (scope.d) {
              scope.addr += " " + scope.d;
            }
            return popup.resize();
          });
          
        });
      }
    };
  });
}).call(this);
